spring.datasource.url=jdbc:mysql://localhost:3306/finanzas
spring.datasource.username=root
spring.datasource.password=gonzalo12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=finanzas-utn-programacion3-clave-secreta-2026-grupof
jwt.expiration=86400000

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Configuración por defecto para servicio UVA (BCRA)
finanzas.uva.api-url=https://api.estadisticasbcra.com/uva
finanzas.uva.api-key=
